export const ENV_VAR_NAMES = {
    LZ_ENV: 'LAYERZERO_ENVIRONMENT',
    LZ_PROVIDER_BUCKET: 'CONFIG_BUCKET_NAME',
    LZ_SUPPORTED_ULNS: 'LAYERZERO_SUPPORTED_ULN_VERSIONS',
    LZ_WALLETS: 'LAYERZERO_WALLETS',
    LZ_METRIC_NAMESPACE: 'LAYERZERO_METRIC_NAMESPACE',
    LZ_METRIC_LOG_GROUP_NAME: 'LAYERZERO_METRIC_LOG_GROUP_NAME',
    LZ_PROVIDER_CONFIG_TYPE: 'PROVIDER_CONFIG_TYPE',
    LZ_AVAILABLE_CHAIN_NAMES: 'LAYERZERO_AVAILABLE_CHAIN_NAMES',
    LZ_KMS_CLOUD_TYPE: 'KMS_CLOUD_TYPE',
    LZ_KMS_IDS: 'LAYERZERO_KMS_IDS',
    LZ_EXTRA_CONTEXT_REQUEST_URL: 'EXTRA_CONTEXT_REQUEST_URL',
    LZ_CDK_DEPLOY_REGION: 'LAYERZERO_CDK_DEPLOY_REGION',
}
